name: Publish React Native App to App Store and Play Store

on:
  release:
    type: [published]

jobs:
  release-ios:
    name: Build and release iOS app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Fastlane
        run: bundle install
      - name: Install packages
        run: yarn install
      - name: Decrypt Google Cloud Key
        run: sh ./scripts/ios-gpg-decrypt.sh
        env:
          ENCRYPT_PASSWORD: ${{ secrets.GPG_ENCRYPT_PASSWORD }}
      - name: Dump secrets to .env
        run: env > .env
        env:
          REQUIRED_ENV: ${{ secrets.REQUIRED_ENV }}
      - name: Build and Upload to TestFlight
        run: bundle exec fastlane build_and_release_to_app_store versionName:${{ github.event.release.tag_name }}
        env:
          VERSION_NAME: ${{ github.event.release.tag_name }}
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}


  release-android:
    name: Build and release Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Setup react-native kernel and increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Install Fastlane
        run: bundle install
      - name: Install packages
        run: yarn install
      - name: Jetifier AndroidX transition 
        run: npx jetify
      - name: Decrypt keystore and Google Credential
        run: sh ./scripts/android-gpg-decrypt.sh
        env:
          ENCRYPT_PASSWORD: ${{ secrets.GPG_ENCRYPT_PASSWORD }}
      - name: Dump secrets to .env
        run: env > .env
        env:
          REQUIRED_ENV: ${{ secrets.REQUIRED_ENV }}
      - name: Bundle and Upload to PlayStore
        run: bundle exec fastlane build_and_release_to_play_store versionName:${{ github.event.release.tag_name }}
        env:
          VERSION_NAME: ${{ github.event.release.tag_name }}
          GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        