# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :build_and_release_to_app_store do |options|
    # Pod Install
  cocoapods(
    podfile: "./ios/Podfile"
  )

    # Set the build number
  increment_build_number(
    build_number: ENV["GITHUB_RUN_NUMBER"],
    xcodeproj: "./ios/the-glew-mobile.xcodeproj"
  )

  # Set the version name
  increment_version_number(
    version_number: ENV["VERSION_NAME"],
    xcodeproj: "./ios/the-glew-mobile.xcodeproj"
  )

  # Create a custom keychain for code signing
  create_keychain(
    name: 'keychain',
    password: 'password',
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  # Import the appstore code signing
  match(
    type: "development",
    keychain_name: 'keychain',
    keychain_password: 'password',
        app_identifier: ["com.testingdevops.glew"],
    readonly: true
  )

    # Disable automatic signing
    update_code_signing_settings(
    use_automatic_signing: false,
    path: "./ios/the-glew-mobile.xcodeproj"
  )

    # Building the iOS app
  gym(
    workspace: "./ios/the-glew-mobile.xcworkspace",
    include_bitcode: true,
    include_symbols: true,
    silent: true,
    clean: true,
    scheme: "the-glew-mobile",
    export_method: "app-store",
    xcargs: {
      PROVISIONING_PROFILE_SPECIFIER: "match Development com.testingdevops.glew"
    }
  )

    # Enable automatic signing
    update_code_signing_settings(
    use_automatic_signing: true,
    path: "./ios/the-glew-mobile.xcodeproj"
  )

  # Upload to testflight
  testflight(
    app_identifier: "com.testingdevops.glew",
    username: "ing.joseapp@gmail.com",
    skip_submission: true,
    skip_waiting_for_build_processing: true
  )
end
